# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.4"
manifest_format = "2.0"
project_hash = "e15001590a918fc35fff9919bebf08e836ddd67c"

[[deps.WandbLogger]]
path = "."
uuid = "62d4785e-023b-4fe3-a3fa-f427ba577678"
version = "1.0.0-DEV"
